project:
  type: website
  output-dir: docs

website:
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
  - id: single_layer
    title: "Single Layer Neural Networks"
    style: docked
    contents:
      - href: topics/single_layer/classification.qmd
        text: Classification
      - href: topics/single_layer/regression.qmd
        text: Regression
      - href: topics/single_layer/single_layer_credit_score.qmd
        text: Credit Score example        
  - id: multi_layer
    title: "Multi Layer Neural Networks"
    style: docked
    contents:
      - href: topics/multi_layer/optim_methods.qmd
        text: Optimization methods
      - href: topics/multi_layer/multi_layer_credit_score.qmd
        text: Regression
  - id: rnn
    title: "Recurrent Neural Networks"
    style: docked
    contents:
      - href: topics/rnn/rnn.qmd
        text: Financial data
      - href: topics/rnn/rnn_cpi.qmd
        text: Seasonal data
        
  - id: exercises
    title: "Exercise sets"
    style: docked
    contents:
      - href: topics/exercises/exercise_1.qmd
        text: Logistic
      - href: topics/exercises/cnn_exercise.qmd
        text: CNN
      - href: topics/exercises/rnn_exercise.qmd
        text: RNN
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
